### ISSUE TITLE
Not supported 

### ISSUE THREAD

**Issue by rajajisubramanian** [raj10071997/Alexa-Voice-Service#18]
We got the PRODCUT_ID and API_KEY from the amazon developer product page. Then we used that into your project, but its not supported. 

What we have added as a skills and endpoint, its not reaching and not able to get the proper response from endpoint. WHY? you have an idea?

**Comment by raj10071997** [comment]
@rajajisubramanian  what is the error that you are getting? can you please show the stack of the errors?

**Comment by rajajisubramanian** [comment]
We are not able generate the certificate file (ca.crt) in windows  instead of using linux commands generate.sh.  After when we are trying to connect with the default IP ("https://10.0.2.2:8443") its give an SSL handshake connection  refused error in the alert dialog. Kindly let me if you need any other information from us

**Comment by raj10071997** [comment]
Sorry I still don't understand what kind of error you are getting and what you are trying to do ? you can generate ca.crt through terminal in windows, this link explains how -"https://github.com/alexa/alexa-avs-sample-app/wiki/Windows".  And if you are following these steps then you must be trying to run the alexa sample app from github?? Then I can't understand where my application comes into picture? Can you please explain what you are doing in detail? I might be able to help you then.

**Comment by rajajisubramanian** [comment]
Okay cool. Actually we created some skills and configuration in amazon of our own product to obtain the amazon alexa voice service. But we are not generate .pem while attempting to create a Endpoint.
So we are get confused, whether .pem file needed while creating endpoint or not?
And more over we have doubt in which URL need to given while creating .cert file for android.
1=>  127.0.0.0
2=> 10.0.2.2
3=>our own server hosted url (which is having ssl certificate)
which one am going to use tell me.

**Comment by raj10071997** [comment]
Sorry for replying late but I couldn't find anything that can help you. If there is anything else that I can help you with feel free to ask.
