### ISSUE TITLE
what is the function of "send ping request every 5 minitus?

### ISSUE THREAD

**Issue by kangshifu** [raj10071997/Alexa-Voice-Service#6]
why should we send ping request to amazon every 5 minitus,and before we sendAudioRequst we must openDownChannel,why?

**Comment by raj10071997** [comment]
The answer to both your questions is given in this link - [https://developer.amazon.com/public/solutions/alexa/alexa-voice-service/docs/managing-an-http-2-connection#ping-timeout](url)

Read - Downchannel Lifecycle and, Ping and Timeout
